### ISSUE TITLE
Ошибка в arh linux при запуске сессии

### ISSUE THREAD

**Issue by iqs-systems** [SlavikMIPT/tgcloud#28]
python telegram_create_session.py
Traceback (most recent call last):
  File "telegram_create_session.py", line 12, in <module>
    client = TelegramClientX(entity, api_id, api_hash, update_workers=None, spawn_read_thread=True)
NameError: name 'entity' is not defined

**Comment by iqs-systems** [comment]
python telegram_create_session.py Traceback (most recent call last):   File "telegram_create_session.py", line 17, in <module>     client.connect()   File "/usr/lib/python3.8/site-packages/telethon/telegram_bare_client.py", line 217, in connect     self.sync_updates()   File "/usr/lib/python3.8/site-packages/telethon/telegram_bare_client.py", line 636, in sync_updates     self.updates.process(self(GetStateRequest()))   File "/usr/lib/python3.8/site-packages/telethon/telegram_bare_client.py", line 500, in __call__     self._reconnect()   File "/usr/lib/python3.8/site-packages/telethon/telegram_bare_client.py", line 299, in _reconnect     return self.connect()   File "/usr/lib/python3.8/site-packages/telethon/telegram_bare_client.py", line 217, in connect     self.sync_updates()   File "/usr/lib/python3.8/site-packages/telethon/telegram_bare_client.py", line 636, in sync_updates     self.updates.process(self(GetStateRequest()))   File "/usr/lib/python3.8/site-packages/telethon/telegram_bare_client.py", line 502, in __call__     raise RuntimeError('Number of retries reached 0 for {}.'.format( RuntimeError: Number of retries reached 0 for GetStateRequest.
